on: [push]

jobs:
  build:
    runs-on: docker
    container:
      image: forge.cptlobster.dev/cptlobster/sbt:alpine-17-jdk-1.10.11
    needs:
      - test
    steps:
      - name: "Install Git and NodeJS"
        run: "apk add git nodejs"
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Login to Forge Packages"
        run: |
          mkdir -p ~/.sbt && \
          echo """
            realm=Gitea Package API @ forge.cptlobster.dev
            host=forge.cptlobster.dev
            user=cptlobster
            password=${{ secrets.PACKAGE_TOKEN }}""" > ~/.sbt/.credentials
      - name: "Build"
        run: "sbt compile"
      - name: "Test"
        run: "sbt test"
      - name: "Publish"
        run: "sbt publish forge"