on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      - "**/LICENSE.md"
      - ".idea/*"
      - "docs/*"

jobs:
  build:
    runs-on: docker
    container:
      image: forge.cptlobster.dev/cptlobster/sbt:alpine-17-jdk-1.10.11
    steps:
      - name: "Install Git and NodeJS"
        run: "apk add git nodejs"
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Login to Forge Packages"
        run: |
          mkdir -p ~/.sbt && \
          echo """
            realm=Gitea Package API
            host=forge.cptlobster.dev
            user=cptlobster
            password=${{ secrets.PACKAGE_TOKEN }}""" > ~/.sbt/.credentials
      - name: "Build"
        run: "sbt compile"
      - name: "Test"
        run: "sbt test"
      - name: "Publish"
        run: "sbt publish"